  CREATE OR REPLACE FORCE VIEW "RIMS"."DEPT_CLG_MAP" ("CLG_CODE", "DEPT_CODE", "DEPT_ENG_NM", "DEPT_KOR_NM", "DEPT_ENG_ABBR", "DEPT_ENG_MOST_ABBR", "CLG_NAME") AS
  select  CLG_CODE
         , DEPT_CODE
         , DEPT_ENG_NM
         , DEPT_KOR_NM
         , DEPT_ENG_ABBR
         , DEPT_ENG_MOST_ABBR
         , CLG_NAME
  from KAIST_CLG_MAP;