/*
분석_제외_대상	RA_ANALS_EXCL_TRGET

일련번호						SN
그룹_타입     - 연구자:U, 학과:D, 단과:C		GROUP_TY
대상_식별자   - USER_ID or DEPT_CODE or COLLEGE_CODE	TRGET_IDNTFR
등록일자						REG_DE
등록자_아이디						REG_USER_ID
*/



  CREATE TABLE "RA_ANALS_EXCL_TRGET"
   ( "SN" NUMBER NOT NULL ENABLE,
	 "GROUP_TY" VARCHAR2(30 BYTE),
	 "TRGET_IDNTFR" VARCHAR2(100 BYTE),
	 "REG_USER_ID" VARCHAR2(30 BYTE),
	 "REG_DATE" DATE NOT NULL ENABLE
   )TABLESPACE "TS_R2RIMS_YU" ;

   COMMENT ON TABLE "RA_ANALS_EXCL_TRGET"  IS '분석_제외_대상';

   CREATE SEQUENCE  "SEQ_ANALS_EXCL_TRGET" ;


   insert into RA_ANALS_EXCL_TRGET(SN, GROUP_TY, TRGET_IDNTFR, REG_USER_ID, REG_DATE)
       values(SEQ_ANALS_EXCL_TRGET.nextval,'U','19200197','ADMIN',sysdate);

   insert into RA_ANALS_EXCL_TRGET(SN, GROUP_TY, TRGET_IDNTFR, REG_USER_ID, REG_DATE)
       values(SEQ_ANALS_EXCL_TRGET.nextval,'D','A000000','ADMIN',sysdate);