REM INSERTING into RI_CODE
SET DEFINE OFF;
Insert into RI_CODE (ID,GUBUN,CODE_VALUE,CODE_DISP,DISP_ORDER,IS_USED,CODE_DISP_ENG,PROPERTY) values (SEQ_RI_CODE.nextval,'ASTOPMENU','home','About YU SCI/KCI',1,'Y','About YU SCI/KCI',null);
Insert into RI_CODE (ID,GUBUN,CODE_VALUE,CODE_DISP,DISP_ORDER,IS_USED,CODE_DISP_ENG,PROPERTY) values (SEQ_RI_CODE.nextval,'ASTOPMENU','researcher','Researcher',2,'Y','Researcher',null);
Insert into RI_CODE (ID,GUBUN,CODE_VALUE,CODE_DISP,DISP_ORDER,IS_USED,CODE_DISP_ENG,PROPERTY) values (SEQ_RI_CODE.nextval,'ASTOPMENU','department','Department',3,'Y','Department',null);
Insert into RI_CODE (ID,GUBUN,CODE_VALUE,CODE_DISP,DISP_ORDER,IS_USED,CODE_DISP_ENG,PROPERTY) values (SEQ_RI_CODE.nextval,'ASTOPMENU','college','College',4,'Y','College',null);
Insert into RI_CODE (ID,GUBUN,CODE_VALUE,CODE_DISP,DISP_ORDER,IS_USED,CODE_DISP_ENG,PROPERTY) values (SEQ_RI_CODE.nextval,'ASTOPMENU','institution','Institution',5,'Y','Institution',null);
Insert into RI_CODE (ID,GUBUN,CODE_VALUE,CODE_DISP,DISP_ORDER,IS_USED,CODE_DISP_ENG,PROPERTY) values (SEQ_RI_CODE.nextval,'ASSUBMENU','home_overview','요약',1,'Y','요약',null);
Insert into RI_CODE (ID,GUBUN,CODE_VALUE,CODE_DISP,DISP_ORDER,IS_USED,CODE_DISP_ENG,PROPERTY) values (SEQ_RI_CODE.nextval,'ASSUBMENU','home_latestArticles','최근게재논문',2,'Y','최근게재논문',null);
Insert into RI_CODE (ID,GUBUN,CODE_VALUE,CODE_DISP,DISP_ORDER,IS_USED,CODE_DISP_ENG,PROPERTY) values (SEQ_RI_CODE.nextval,'ASSUBMENU','home_publicationSCI','연도별 논문건수',3,'Y','연도별 논문건수',null);
Insert into RI_CODE (ID,GUBUN,CODE_VALUE,CODE_DISP,DISP_ORDER,IS_USED,CODE_DISP_ENG,PROPERTY) values (SEQ_RI_CODE.nextval,'ASSUBMENU','home_jcrRankingByCategory','학술지 분야별 IF',4,'Y','학술지 분야별 IF',null);
Insert into RI_CODE (ID,GUBUN,CODE_VALUE,CODE_DISP,DISP_ORDER,IS_USED,CODE_DISP_ENG,PROPERTY) values (SEQ_RI_CODE.nextval,'ASSUBMENU','home_subjectJcrRanking','IF Ranking by Cat',5,'Y','IF Ranking by Cat',null);
Insert into RI_CODE (ID,GUBUN,CODE_VALUE,CODE_DISP,DISP_ORDER,IS_USED,CODE_DISP_ENG,PROPERTY) values (SEQ_RI_CODE.nextval,'ASSUBMENU','home_deptJournal','연도별 최다 논문 게재 학술지 현황',7,'Y','연도별 최다 논문 게재 학술지 현황',null);
Insert into RI_CODE (ID,GUBUN,CODE_VALUE,CODE_DISP,DISP_ORDER,IS_USED,CODE_DISP_ENG,PROPERTY) values (SEQ_RI_CODE.nextval,'ASSUBMENU','researcher_overview','요약',12,'Y','요약',null);
Insert into RI_CODE (ID,GUBUN,CODE_VALUE,CODE_DISP,DISP_ORDER,IS_USED,CODE_DISP_ENG,PROPERTY) values (SEQ_RI_CODE.nextval,'ASSUBMENU','researcher_profile','프로파일',13,'Y','프로파일',null);
Insert into RI_CODE (ID,GUBUN,CODE_VALUE,CODE_DISP,DISP_ORDER,IS_USED,CODE_DISP_ENG,PROPERTY) values (SEQ_RI_CODE.nextval,'ASSUBMENU','researcher_publication','연도별 논문건수',14,'Y','연도별 논문건수',null);
Insert into RI_CODE (ID,GUBUN,CODE_VALUE,CODE_DISP,DISP_ORDER,IS_USED,CODE_DISP_ENG,PROPERTY) values (SEQ_RI_CODE.nextval,'ASSUBMENU','researcher_h-index','H-index',15,'Y','H-index',null);
Insert into RI_CODE (ID,GUBUN,CODE_VALUE,CODE_DISP,DISP_ORDER,IS_USED,CODE_DISP_ENG,PROPERTY) values (SEQ_RI_CODE.nextval,'ASSUBMENU','researcher_trends','논문 피인용 현황',16,'Y','논문 피인용 현황',null);
Insert into RI_CODE (ID,GUBUN,CODE_VALUE,CODE_DISP,DISP_ORDER,IS_USED,CODE_DISP_ENG,PROPERTY) values (SEQ_RI_CODE.nextval,'ASSUBMENU','researcher_coauthor','공동연구자 네트워크',17,'Y','공동연구자 네트워크',null);
Insert into RI_CODE (ID,GUBUN,CODE_VALUE,CODE_DISP,DISP_ORDER,IS_USED,CODE_DISP_ENG,PROPERTY) values (SEQ_RI_CODE.nextval,'ASSUBMENU','researcher_similar','유사 연구자 조회',18,'Y','유사 연구자 조회',null);
Insert into RI_CODE (ID,GUBUN,CODE_VALUE,CODE_DISP,DISP_ORDER,IS_USED,CODE_DISP_ENG,PROPERTY) values (SEQ_RI_CODE.nextval,'ASSUBMENU','researcher_journals','연도별 최다 논문 게재 학술지 현황',19,'Y','연도별 최다 논문 게재 학술지 현황',null);
Insert into RI_CODE (ID,GUBUN,CODE_VALUE,CODE_DISP,DISP_ORDER,IS_USED,CODE_DISP_ENG,PROPERTY) values (SEQ_RI_CODE.nextval,'ASSUBMENU','researcher_patentTrend','특허출원 현황',19,'Y','특허출원 현황',null);
Insert into RI_CODE (ID,GUBUN,CODE_VALUE,CODE_DISP,DISP_ORDER,IS_USED,CODE_DISP_ENG,PROPERTY) values (SEQ_RI_CODE.nextval,'ASSUBMENU','researcher_techTrans','기술이전 현황',19,'Y','기술이전 현황',null);
Insert into RI_CODE (ID,GUBUN,CODE_VALUE,CODE_DISP,DISP_ORDER,IS_USED,CODE_DISP_ENG,PROPERTY) values (SEQ_RI_CODE.nextval,'ASSUBMENU','department_overview','요약',20,'Y','요약',null);
Insert into RI_CODE (ID,GUBUN,CODE_VALUE,CODE_DISP,DISP_ORDER,IS_USED,CODE_DISP_ENG,PROPERTY) values (SEQ_RI_CODE.nextval,'ASSUBMENU','department_latestArticles','최근게재논문',21,'Y','최근게재논문',null);
Insert into RI_CODE (ID,GUBUN,CODE_VALUE,CODE_DISP,DISP_ORDER,IS_USED,CODE_DISP_ENG,PROPERTY) values (SEQ_RI_CODE.nextval,'ASSUBMENU','department_coAuthor','학과간 네트워크',22,'Y','학과간 네트워크',null);
Insert into RI_CODE (ID,GUBUN,CODE_VALUE,CODE_DISP,DISP_ORDER,IS_USED,CODE_DISP_ENG,PROPERTY) values (SEQ_RI_CODE.nextval,'ASSUBMENU','department_coAuthorWithinSameDepartment','학과내 네트워크',23,'Y','학과내 네트워크',null);
Insert into RI_CODE (ID,GUBUN,CODE_VALUE,CODE_DISP,DISP_ORDER,IS_USED,CODE_DISP_ENG,PROPERTY) values (SEQ_RI_CODE.nextval,'ASSUBMENU','department_trendNoArts','연도별 논문건수',24,'Y','연도별 논문건수',null);
Insert into RI_CODE (ID,GUBUN,CODE_VALUE,CODE_DISP,DISP_ORDER,IS_USED,CODE_DISP_ENG,PROPERTY) values (SEQ_RI_CODE.nextval,'ASSUBMENU','department_trendIF','평균 IF 현황',25,'Y','평균 IF 현황',null);
Insert into RI_CODE (ID,GUBUN,CODE_VALUE,CODE_DISP,DISP_ORDER,IS_USED,CODE_DISP_ENG,PROPERTY) values (SEQ_RI_CODE.nextval,'ASSUBMENU','department_citation','논문 피인용 현황',26,'Y','논문 피인용 현황',null);
Insert into RI_CODE (ID,GUBUN,CODE_VALUE,CODE_DISP,DISP_ORDER,IS_USED,CODE_DISP_ENG,PROPERTY) values (SEQ_RI_CODE.nextval,'ASSUBMENU','department_h-index','H-index',27,'Y','H-index',null);
Insert into RI_CODE (ID,GUBUN,CODE_VALUE,CODE_DISP,DISP_ORDER,IS_USED,CODE_DISP_ENG,PROPERTY) values (SEQ_RI_CODE.nextval,'ASSUBMENU','department_subject','연도별 최다 논문 게재 연구분야 현황',28,'Y','연도별 최다 논문 게재 연구분야 현황',null);
Insert into RI_CODE (ID,GUBUN,CODE_VALUE,CODE_DISP,DISP_ORDER,IS_USED,CODE_DISP_ENG,PROPERTY) values (SEQ_RI_CODE.nextval,'ASSUBMENU','department_journal','연도별 최다 논문 게재 학술지 현황',29,'Y','연도별 최다 논문 게재 학술지 현황',null);
Insert into RI_CODE (ID,GUBUN,CODE_VALUE,CODE_DISP,DISP_ORDER,IS_USED,CODE_DISP_ENG,PROPERTY) values (SEQ_RI_CODE.nextval,'ASSUBMENU','department_trendNoPats','특허출원 현황',30,'Y','특허출원 현황',null);
Insert into RI_CODE (ID,GUBUN,CODE_VALUE,CODE_DISP,DISP_ORDER,IS_USED,CODE_DISP_ENG,PROPERTY) values (SEQ_RI_CODE.nextval,'ASSUBMENU','department_techTrans','기술이전 현황',31,'Y','기술이전 현황',null);
Insert into RI_CODE (ID,GUBUN,CODE_VALUE,CODE_DISP,DISP_ORDER,IS_USED,CODE_DISP_ENG,PROPERTY) values (SEQ_RI_CODE.nextval,'ASSUBMENU','college_overview','요약',34,'Y','요약',null);
Insert into RI_CODE (ID,GUBUN,CODE_VALUE,CODE_DISP,DISP_ORDER,IS_USED,CODE_DISP_ENG,PROPERTY) values (SEQ_RI_CODE.nextval,'ASSUBMENU','college_latestArticles','최근게재논문',35,'Y','최근게재논문',null);
Insert into RI_CODE (ID,GUBUN,CODE_VALUE,CODE_DISP,DISP_ORDER,IS_USED,CODE_DISP_ENG,PROPERTY) values (SEQ_RI_CODE.nextval,'ASSUBMENU','college_publicationByHindex','H-index',36,'Y','H-index',null);
Insert into RI_CODE (ID,GUBUN,CODE_VALUE,CODE_DISP,DISP_ORDER,IS_USED,CODE_DISP_ENG,PROPERTY) values (SEQ_RI_CODE.nextval,'ASSUBMENU','college_departNoArts','학과별 논문 건수',37,'Y','학과별 논문 건수',null);
Insert into RI_CODE (ID,GUBUN,CODE_VALUE,CODE_DISP,DISP_ORDER,IS_USED,CODE_DISP_ENG,PROPERTY) values (SEQ_RI_CODE.nextval,'ASSUBMENU','college_departIF','학과별 평균 IF 현황',38,'Y','학과별 평균 IF 현황',null);
Insert into RI_CODE (ID,GUBUN,CODE_VALUE,CODE_DISP,DISP_ORDER,IS_USED,CODE_DISP_ENG,PROPERTY) values (SEQ_RI_CODE.nextval,'ASSUBMENU','college_departTimeCited','학과별 평균 논문 피인용현황',39,'Y','학과별 평균 논문 피인용현황',null);
Insert into RI_CODE (ID,GUBUN,CODE_VALUE,CODE_DISP,DISP_ORDER,IS_USED,CODE_DISP_ENG,PROPERTY) values (SEQ_RI_CODE.nextval,'ASSUBMENU','college_departCoAuthor','학과별 공동연구 네트워크',40,'Y','학과별 공동연구 네트워크',null);
Insert into RI_CODE (ID,GUBUN,CODE_VALUE,CODE_DISP,DISP_ORDER,IS_USED,CODE_DISP_ENG,PROPERTY) values (SEQ_RI_CODE.nextval,'ASSUBMENU','college_departNoPats','특허출원 현황',41,'Y','특허출원 현황',null);
Insert into RI_CODE (ID,GUBUN,CODE_VALUE,CODE_DISP,DISP_ORDER,IS_USED,CODE_DISP_ENG,PROPERTY) values (SEQ_RI_CODE.nextval,'ASSUBMENU','college_techTrans','기술이전 현황',42,'Y','기술이전 현황',null);
Insert into RI_CODE (ID,GUBUN,CODE_VALUE,CODE_DISP,DISP_ORDER,IS_USED,CODE_DISP_ENG,PROPERTY) values (SEQ_RI_CODE.nextval,'ASSUBMENU','institution_byHindex','H-index',44,'Y','H-index',null);
Insert into RI_CODE (ID,GUBUN,CODE_VALUE,CODE_DISP,DISP_ORDER,IS_USED,CODE_DISP_ENG,PROPERTY) values (SEQ_RI_CODE.nextval,'ASSUBMENU','institution_byPublications','연구자별 논문수',45,'Y','연구자별 논문수',null);
Insert into RI_CODE (ID,GUBUN,CODE_VALUE,CODE_DISP,DISP_ORDER,IS_USED,CODE_DISP_ENG,PROPERTY) values (SEQ_RI_CODE.nextval,'ASSUBMENU','institution_topArticles','논문별 피인용수',46,'Y','논문별 피인용수',null);
Insert into RI_CODE (ID,GUBUN,CODE_VALUE,CODE_DISP,DISP_ORDER,IS_USED,CODE_DISP_ENG,PROPERTY) values (SEQ_RI_CODE.nextval,'ASSUBMENU','institution_departNoArts','논문 건수',47,'Y','논문 건수',null);
Insert into RI_CODE (ID,GUBUN,CODE_VALUE,CODE_DISP,DISP_ORDER,IS_USED,CODE_DISP_ENG,PROPERTY) values (SEQ_RI_CODE.nextval,'ASSUBMENU','institution_departIF','평균 IF 현황',48,'Y','평균 IF 현황',null);
Insert into RI_CODE (ID,GUBUN,CODE_VALUE,CODE_DISP,DISP_ORDER,IS_USED,CODE_DISP_ENG,PROPERTY) values (SEQ_RI_CODE.nextval,'ASSUBMENU','institution_departTimeCited','평균 논문 피인용현황',49,'Y','평균 논문 피인용현황',null);
Insert into RI_CODE (ID,GUBUN,CODE_VALUE,CODE_DISP,DISP_ORDER,IS_USED,CODE_DISP_ENG,PROPERTY) values (SEQ_RI_CODE.nextval,'ASSUBMENU','institution_departCoAuthor','공동연구 네트워크',50,'Y','공동연구 네트워크',null);
Insert into RI_CODE (ID,GUBUN,CODE_VALUE,CODE_DISP,DISP_ORDER,IS_USED,CODE_DISP_ENG,PROPERTY) values (SEQ_RI_CODE.nextval,'ASSUBMENU','institution_departNoPats','특허출원 현황',51,'Y','특허출원 현황',null);
Insert into RI_CODE (ID,GUBUN,CODE_VALUE,CODE_DISP,DISP_ORDER,IS_USED,CODE_DISP_ENG,PROPERTY) values (SEQ_RI_CODE.nextval,'ASSUBMENU','institution_techTrans','기술이전 현황',52,'Y','기술이전 현황',null);
