 CREATE OR REPLACE FORCE VIEW "RI_CODE" ("GUBUN", "CODE_VALUE", "CODE_DISP", "CODE_DISP_ENG", "DISP_ORDER", "IS_USED", "PROPERTY" ) AS
 select GUBUN, CODE_VALUE, CODE_DISP, CODE_DISP_ENG, DISP_ORDER, IS_USED, PROPERTY from RI_CODE_COMMON
	union all
 select GUBUN, CODE_VALUE, CODE_DISP, CODE_DISP as CODE_DISP_ENG, DISP_ORDER, IS_USED, '' as PROPERTY from RI_CODE_ORG