  CREATE TABLE "RI_TECHTRANS_PARTI"
   ( "TECHTRANS_ID" NUMBER(10,0) NOT NULL ENABLE,
	"SEQ_AUTHOR" NUMBER(6,0) NOT NULL ENABLE,
	"DISP_ORDER" NUMBER(6,0),
	"PRTCPNT_ID" VARCHAR2(20 BYTE),
	"PRTCPNT_NM" VARCHAR2(100 BYTE),
	"PRTCPNT_FULL_NM" VARCHAR2(100 BYTE),
	"RECORD_STATUS" CHAR(1 BYTE),
	"TPI_DVS_CD" VARCHAR2(20 BYTE),
	"BLNG_AGC_CD" VARCHAR2(6 BYTE),
	"BLNG_AGC_NM" VARCHAR2(200 BYTE),
	"TPI_RATE" VARCHAR2(3 BYTE),
	"REG_USER_ID" VARCHAR2(20 BYTE),
	"REG_DATE" DATE,
	"MOD_USER_ID" VARCHAR2(20 BYTE),
	"MOD_DATE" DATE,
	"DEL_DVS_CD" CHAR(1 BYTE)
   ) TABLESPACE "TS_R2RIMS_YU" ;


   -- 기술이전_참여자_입금액 RI_TECHTRANS_PARTI_RPMAMT
   /*
    * 제어번호		"TECHTRANS_ID" NUMBER(10,0) NOT NULL ENABLE,
    * 입금일련번호  "SEQ_ROYALTY"
    * 일련번호 		"SEQ_NO"
    * 입급년도 		"RPM_YEAR"
    * 입금일자		"RPM_DATE"
    * 참여자ID	    "PRTCPNT_ID"
    * 입금액		"RPM_AMT"
    * 등록자ID      "REG_USER_ID"
    * 등록일자      "REG_DATE"
    * 수정일자      "MOD_DATE"
    * 수정자ID      "MOD_USER_ID"
    */


   CREATE TABLE "RI_TECHTRANS_PARTI_RPMAMT"
   ( "TECHTRANS_ID" NUMBER(10,0) NOT NULL ENABLE,
	 "SEQ_ROYALTY" NUMBER(6,0) NOT NULL ENABLE,
	 "SEQ_NO" NUMBER(6,0) NOT NULL ENABLE,
	 "RPM_YEAR" VARCHAR2(4 BYTE),
	 "RPM_DATE" VARCHAR2(8 BYTE),
	 "RPM_AMT" VARCHAR2(13 BYTE),
	 "PRTCPNT_ID" VARCHAR2(20 BYTE),
	 "REG_USER_ID" VARCHAR2(20 BYTE),
	 "REG_DATE" DATE,
	 "MOD_USER_ID" VARCHAR2(20 BYTE),
	 "MOD_DATE" DATE
   ) TABLESPACE "TS_R2RIMS_YU" ;