
/* 1) create PNTTM_ID */
select to_char(sysdate, 'YYYYMMDDHH24MISS') as PNTTM_ID from dual
;

/* truncate RAWDATA */
TRUNCATE TABLE RI_STATS_ARTICLE_RAWDATA;
TRUNCATE TABLE RI_STATS_PATENT_RAWDATA;
TRUNCATE TABLE RI_STATS_CONFERENCE_RAWDATA;
TRUNCATE TABLE RI_STATS_FUNDING_RAWDATA;

/* sequence init */
DROP SEQUENCE SEQ_RI_STATS_ARTICLE_RAWDATA;
DROP SEQUENCE SEQ_RI_STATS_PATENT_RAWDATA;
DROP SEQUENCE SEQ_RI_STATS_CONF_RAWDATA;
DROP SEQUENCE SEQ_RI_STATS_FUNDING_RAWDATA;

CREATE SEQUENCE SEQ_RI_STATS_ARTICLE_RAWDATA MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE SEQ_RI_STATS_PATENT_RAWDATA MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE SEQ_RI_STATS_CONF_RAWDATA MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE SEQ_RI_STATS_FUNDING_RAWDATA MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;


/* insert RI_STATS_FUNDING_RAWDATA */
insert into RI_STATS_FUNDING_RAWDATA
  select SEQ_RI_STATS_FUNDING_RAWDATA.nextval
    ,'20180618130831' as PNTTM_ID
    ,RF.FUNDING_ID
    ,RF.SBJT_NO
    ,RF.AGC_SBJT_NO
    ,RF.RSCH_CMCM_YM
    ,substr(RSCH_CMCM_YM,1,4) as RSCH_YEAR
    ,RF.RSCH_END_YM
    ,RF.RSCH_SBJT_NM
    ,RF.RSRCCT_SPPT_DVS_CD
    ,RF.RSRCCT_SPPT_AGC_NM
    ,RF.BIZ_NM
    ,RF.MNY_YR_SBJT_YN
    ,RF.CPT_GOV_OFFIC_NM
    ,RF.ERP_ID
    ,RF.OVERALL_FLAG
    ,RF.SRC
    ,RF.APPR_DVS_CD
    ,RF.MOD_DATE
    ,RF.REG_DATE
    ,RF.RSCH_SBJT_STDY_SPHE_CD
    ,RF.DEL_DVS_CD
    ,RF.IS_FIXED
    ,TA.TOT_RSRCCT
    ,FP.SEQ_PARTI
    ,FP.PRTCPNT_ID
    ,FP.PRTCPNT_NM
    ,FP.TPI_DVS_CD
    ,FP.BLNG_AGC_NM
    ,RU.GUBUN
    ,CASE WHEN (substr(RF.RSCH_CMCM_YM,1,6) < substr(RU.APTM_DATE,1,6)) THEN 'B' ELSE 'A' END as ENTER_GUBUN
    ,RU.KOR_NM
    ,RU.SEX_DVS_CD
    ,RU.NTNT_CD
    ,DECODE(RU.NTNT_CD,'KO','국내','국외') ntnt_gubun
    ,RU.APTM_DATE
    ,RU.HLDOF_YN
    ,RU.RETR_DATE
    ,RU.DEPT_KOR
    ,RU.CLG_CD
    ,RU.GRADE1
    ,DECODE(RU.GRADE1, '교수',1, '조교수',1, '부교수',1, '학생',3, 2) grade_gubun
    ,RU.GROUP_DEPT
    ,RU.GROUP_CLG
    ,RU.U_ID
  from RI_FUNDING RF
    join RI_FUNDING_PARTI FP on (RF.FUNDING_ID=FP.FUNDING_ID)
    join RI_USER RU on (NVL(FP.PRTCPNT_ID,'0') = RU.USER_ID)
    left join (select FUNDING_ID, sum(TOT_RSRCCT)  as TOT_RSRCCT from RI_FUNDING_DETAIL where NVL(DEL_DVS_CD,'N') != 'Y' group by FUNDING_ID) TA on (RF.FUNDING_ID = TA.FUNDING_ID)
  where NVL(RF.DEL_DVS_CD,'N') != 'Y'
        and NVL(FP.DEL_DVS_CD,'N') != 'Y'
        and NVL(RU.DEL_DVS_CD,'N') != 'Y'
;

/* insert RI_STATS_CONFERENCE_RAWDATA */
insert into RI_STATS_CONFERENCE_RAWDATA
  select SEQ_RI_STATS_CONF_RAWDATA.nextval
    ,'20180618130831' as PNTTM_ID
    ,TA.CONFERENCE_ID
    ,TA.SCJNL_DVS_CD
    ,ta.ORG_LANG_PPR_NM
    ,substr(TA.ANCM_DATE,1,4) PUBYEAR
    ,TA.ANCM_DATE
    ,TA.SCJNL_NM
    ,ta.PBLC_PLC_NM
    ,TA.ISSN_NO
    ,TA.VOLUME
    ,TA.STT_PAGE
    ,TA.END_PAGE
    ,TA.DOI
    ,TA.ABST_CNTN
    ,TA.PBLC_NTN_CD
    ,TA.ANCM_STLE_CD
    ,TA.ID_SCI
    ,TA.ID_SCOPUS
    ,TA.ID_KCI
    ,TA.IMPCT_FCTR
    ,TA.TC
    ,TA.TC_DATE
    ,TA.APPR_DVS_CD
    ,TA.APPR_DATE
    ,TB.SEQ_AUTHOR
    ,TB.PRTCPNT_ID
    ,TB.PRTCPNT_NM
    ,TB.TPI_DVS_CD
    ,TB.BLNG_AGC_NM
    ,TC.GUBUN
    ,CASE WHEN (substr(TA.ANCM_DATE,1,6) < substr(TC.APTM_DATE,1,6)) THEN 'B' ELSE 'A' END as ENTER_GUBUN
    ,TC.KOR_NM
    ,TC.SEX_DVS_CD
    ,TC.NTNT_CD
    ,DECODE(TC.NTNT_CD,'KO','국내','국외') ntnt_gubun
    ,TC.APTM_DATE
    ,TC.HLDOF_YN
    ,TC.RETR_DATE
    ,TC.DEPT_KOR
    ,TC.CLG_CD
    ,TC.GRADE1
    ,DECODE(TC.GRADE1, '교수',1, '조교수',1, '부교수',1, '학생',3, 2) grade_gubun
    ,TC.GROUP_DEPT
    ,TC.GROUP_CLG
    ,TC.U_ID
  from RI_CONFERENCE TA
    join RI_CONFERENCE_PARTI TB on (TA.CONFERENCE_ID = TB.CONFERENCE_ID)
    join RI_USER TC on (TB.PRTCPNT_ID = TC.USER_ID)
  where  NVL(TA.del_dvs_cd,'N') != 'Y'
         AND NVL(TB.DEL_DVS_CD,'N') != 'Y'
         AND NVL(TC.DEL_DVS_CD,'N') != 'Y'
;

/* insert RI_STATS_PATENT_RAWDATA */
insert into RI_STATS_PATENT_RAWDATA
  SELECT SEQ_RI_STATS_PATENT_RAWDATA.nextval,
    '20180618130831' as PNTTM_ID,
    TA.patent_id,
    TA.acqs_dvs_cd,
    TA.acqs_ntn_dvs_cd,
    TA.itl_ppr_rgt_dvs_cd,
    TA.status,
    SUBSTR(TA.appl_reg_date,1,4) as APPLYEAR,
    SUBSTR(TA.itl_ppr_rgt_reg_date,1,4) as ITLYEAR,
    TA.itl_ppr_rgt_nm,
    TA.itl_ppr_rgt_reg_date,
    TA.itl_ppr_rgt_reg_no,
    TA.appl_reg_ntn_cd,
    TA.appl_reg_date,
    TA.appl_reg_no,
    TA.pat_cls_cd,
    TA.appl_regt_nm,
    TA.APPR_DVS_CD,
    TA.APPR_DATE,
    TB.SEQ_AUTHOR,
    TB.prtcpnt_id,
    TB.PRTCPNT_NM,
    TB.TPI_DVS_CD,
    TB.BLNG_AGC_NM,
    TC.GUBUN,
    CASE WHEN (TA.itl_ppr_rgt_reg_date < TC.aptm_date) THEN 'B' ELSE 'A' END as ENTER_GUBUN,
    TC.KOR_NM,
    TC.SEX_DVS_CD,
    TC.NTNT_CD,
    DECODE(TC.NTNT_CD,'KO','국내','국외') ntnt_gubun,
    TC.APTM_DATE,
    TC.HLDOF_YN,
    TC.RETR_DATE,
    TC.DEPT_KOR,
    TC.CLG_CD,
    TC.GRADE1,
    DECODE(TC.GRADE1, '교수',1, '조교수',1, '부교수',1, '학생',3, 2) grade_gubun,
    TC.GROUP_DEPT,
    TC.GROUP_CLG,
    TC.U_ID,
    TA.SRC_ID
  FROM RI_PATENT TA
    join RI_PATENT_PARTI TB on (TA.PATENT_ID = TB.PATENT_ID)
    join RI_USER TC on (TB.PRTCPNT_ID = TC.USER_ID)
  WHERE NVL(TA.DEL_DVS_CD,'N') != 'Y'
        AND NVL(TB.DEL_DVS_CD,'N') != 'Y'
        AND NVL(TC.DEL_DVS_CD,'N') != 'Y'
;

/* insert RI_STATS_ARTICLE_RAWDATA */
insert into RI_STATS_ARTICLE_RAWDATA
  SELECT
    SEQ_RI_STATS_ARTICLE_RAWDATA.nextval,
    '20180618130831' as PNTTM_ID,
    TA.ARTICLE_ID,
    TA.ORG_LANG_PPR_NM,
    TA.DIFF_LANG_PPR_NM,
    TA.SCJNL_NM,
    TA.SCJNL_DVS_CD,
    TA.OVRS_EXCLNC_SCJNL_PBLC_YN,
    TA.PBLC_PLC_NM,
    TA.PBLC_YM,
    SUBSTR(TA.PBLC_YM,1,4) as PUBYEAR,
    case when TA.PBLC_YM = 'ACCEPT' then null else SUBSTR(TA.PBLC_YM,5,2) end as PBLC_MONTH,
    TA.PBLC_NTN_CD,
    TA.PPR_LANG_DVS_CD,
    TA.ISSN_NO,
    TA.VOLUME,
    TA.ISSUE,
    TA.STT_PAGE,
    TA.END_PAGE,
    TA.TOTAL_ATHR_CNT,
    TA.DOI,
    TA.ABST_CNTN,
    TA.ID_SCI,
    TA.ID_SCOPUS,
    TA.ID_KCI,
    TA.ORNIF,
    TRIM(TA.IMPCT_FCTR) as IMPCT_FCTR,
    TD.IMPACT,
    TA.TC,
    TA.TC_DATE,
    TA.SCP_TC,
    TA.SCP_TC_DATE,
    TA.KCI_TC,
    TA.KCI_TC_DATE,
    TA.RSRCHACPS_STDY_SPHE_CD,
    TA.APPR_DVS_CD,
    TA.APPR_DATE,
    TA.VRFC_SRC_DVS_CD,
    TA.DEL_DVS_CD,
    TA.INSTT_RSLT_AT,
    TA.OPEN_ACCES_AT,
    CASE WHEN (TA.scjnl_dvs_cd || NVL(TA.OVRS_EXCLNC_SCJNL_PBLC_YN, '9') <= '14') THEN '11' ELSE TA.SCJNL_DVS_CD || TA.OVRS_EXCLNC_SCJNL_PBLC_YN END as JNL_GUBUN,
    DECODE(TA.PBLC_YM, 'ACCECT', 'A', 'P') as PUBLISH_GUBUN,
    TA.TECH_CLS_6T_CD,
    TB.SEQ_AUTHOR,
    TB.PRTCPNT_ID,
    TB.PRTCPNT_NM,
    TB.PRTCPNT_FULL_NM,
    TB.TPI_DVS_CD,
    TB.BLNG_AGC_NM,
    TC.GUBUN,
    CASE WHEN (TA.PBLC_YM < SUBSTR(TC.APTM_DATE,1,6)) THEN 'B' ELSE 'A' END as ENTER_GUBUN,
    TC.KOR_NM,
    TC.SEX_DVS_CD,
    TC.NTNT_CD,
    DECODE(TC.NTNT_CD,'KO','국내','국외') ntnt_gubun,
    TC.APTM_DATE,
    TC.HLDOF_YN,
    TC.RETR_DATE,
    TC.DEPT_KOR,
    TC.CLG_CD,
    TC.GRADE1,
    DECODE(TC.GRADE1, '교수',1, '조교수',1, '부교수',1, '학생',3, 2) grade_gubun,
    TC.GROUP_DEPT,
    TC.GROUP_CLG,
    TC.U_ID
  from RI_ARTICLE TA
    join RI_ARTICLE_PARTI TB on (TA.ARTICLE_ID = TB.ARTICLE_ID)
    join RI_USER TC on (TB.PRTCPNT_ID = TC.USER_ID)
    left join (
                select ISSN, MAX(IMPACT) as IMPACT  from JCR_CAT_RANK where PRODYEAR = (select max(prodyear) from JCR_CAT_RANK) group by PRODYEAR, ISSN
              ) TD on (TA.ISSN_NO = TD.ISSN)
  where NVL(TA.del_dvs_cd,'N') != 'Y'
        and NVL(TB.del_dvs_cd,'N') != 'Y'
        and NVL(TC.DEL_DVS_CD, 'N') != 'Y'
;